package tqs.tomas.ua.SeleniumDriver;
// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TqsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void tqs() {
    // Test name: tqs
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("http://demo.redmine.org/");
    // 2 | setWindowSize | 1160x773 | 
    driver.manage().window().setSize(new Dimension(1160, 773));
    // 3 | click | linkText=Entrar | 
    driver.findElement(By.linkText("Entrar")).click();
    // 4 | type | id=username | tomas99batista
    driver.findElement(By.id("username")).sendKeys("tomas99batista");
    // 5 | type | id=password | tomas12345
    driver.findElement(By.id("password")).sendKeys("tomas12345");
    // 6 | click | name=login | 
    driver.findElement(By.name("login")).click();
    // 7 | assertElementPresent | linkText=tomas99batista | 
    {
      List<WebElement> elements = driver.findElements(By.linkText("tomas99batista"));
      assert(elements.size() > 0);
    }
    // 8 | click | linkText=Sair | 
    driver.findElement(By.linkText("Sair")).click();
    // 9 | assertElementPresent | linkText=Entrar | 
    {
      List<WebElement> elements = driver.findElements(By.linkText("Entrar"));
      assert(elements.size() > 0);
    }
  }
}
